### ISSUE TITLE
🐛 Bug: Parse mode doesn't like org-scoped registries

### ISSUE THREAD

**Issue by james-nash** [johnnyreilly/azdo-npm-auth#25]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/johnnyreilly/azdo-npm-auth/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Running `npx -y --registry https://registry.npmjs.org azdo-npm-auth` on a project whose `.npmrc` uses an [org-scoped registry config](https://docs.npmjs.com/cli/v9/configuring-npm/npmrc#auth-related-configuration), like:

```
@myorg:registry=https://pkgs.internal-repo.myorg.com/foo/bar/baz
```

...should just work™️ as per the README.

### Actual

The command fails with the error: `Error parsing project .npmrc.`

### Additional Info

I presume this is to do with the org scoping, because when I removed the `@orgname:` prefix in my `.npmrc`, it worked fine.

**Comment by johnnyreilly** [comment]
You might be onto something here!

**Comment by james-nash** [comment]
I _think_, you shouldn't duplicate the `@myorg:registry=URL` bit in the user's `~/.npmrc`. IMHO, that's a per-project choice between the unscoped "I want `npm` to load _all_ packages from this custom registry" versus "I want only packages whose names begin with `@myorg/...` to be loaded form this custom registry, and anything else comes from npmjs.com as usual".

All we need in the user's `~/.npmrc` is the auth details for each registry.

So, I would suggest the behaviour should be:

* Look for `registry=[URL]` _and_ `@[org-name]:registery=[URL]` lines in the project `.npmrc`.
* For each URL that you find, add a corresponding...
  ```ini
  ; begin auth token
  //[URL]:username=...
  ...
  ; end auth token
  ```
  ...block to the user's `.npmrc`.

Considering that folks might be using `azdo-npm-auth` with multiple projects on their machine, it would be nice if it was smart enough to not overwrite the user's `~/.npmrc` , but intelligently find and update existing entries with a matching URL, and only add new ones when needed.

**Comment by johnnyreilly** [comment]
So it's just the parsing that you think should be amended?

So if it could cope with

```npmrc
@myorg:registry=https://pkgs.internal-repo.myorg.com/foo/bar/baz
```

as well as

```npmrc
registry=https://pkgs.internal-repo.myorg.com/foo/bar/baz
```

it'd be fine?

> Considering that folks might be using azdo-npm-auth with multiple projects on their machine, it would be nice if it was smart enough to not overwrite the user's ~/.npmrc , but intelligently find and update existing entries with a matching URL, and only add new ones when needed.

I take you're point on this, but I'd like to tackle this separately

**Comment by james-nash** [comment]
Yup, I think that's correct.

Agreed that the multi registry auth stuff feels more like an enhancement. I'm happy to write up a separate issue for that if it helps.
